### PR TITLE
fix errors in OrgParserTest

### LINKED ISSUE #3: 11 unit test errors in `OrgParserTest`
as of https://github.com/JurajKubelka/OrgMode/commit/3983549dc686ba3e4edf11b552369954cd60c61e running in Pharo 9.0
Screenshot from 2022-09-06 22-11-43

### PR DESCRIPTION
**Pull request by capsulecorplab**
resolve #3

### CODE REVIEW

**Comment by capsulecorplab** [comment]
managed to resolve 10/11 errors encountered in #3 

Screenshot from 2022-09-07 00-05-02

**Comment by capsulecorplab** [comment]
Encountering the following stack trace while trying to run `testHeadingWithProperties`. @JurajKubelka thoughts?

Screenshot from 2022-09-07 00-05-12

**Comment by JurajKubelka** [comment]
Hi @capsulecorplab!

I have recently fixed the baseline and couple of tests.
I think couple of methods disappeared. I have not checked why and when it happened.

**Comment by capsulecorplab** [comment]
Cool! Closing this PR as `OrgParserTest` seem to be all passing as per https://github.com/JurajKubelka/OrgMode/commit/f18b0545873f152fdd92b457bad0025e330bea77

**Comment by JurajKubelka** [comment]
Thank you!

**Pull request closed without merging**
